CAMERA_SSID=
CAMERA_MARKED_VIDEO_DIRS="CARDV/EMR/,CARDV/EMR_E/"
VIDEO_EXTENDED_MARKED_WINDOW=3
VIDEO_EXTENSIONS=".TS,.MP4"
VIDEO_RECORDING_WINDOW=2
#VIDEO_DOWNLOAD_DIR=/var/fitcamx-crawler/videos
UPLOAD_TARGET=gs://your-bucket
GOOGLE_APPLICATION_CREDENTIALS=/etc/google-serviceaccount.json
HEARTBEAT_INTERVAL=60
